string message = "";
message += "Hello";
message += ",";
message += " ";
message += "World!";
Console.WriteLine(message);
Console.WriteLine("Przejście do\nnowej linii.");
Console.WriteLine("tabulacja\tpozioma. ");
Console.WriteLine("Tabulacja\npionowa. ");
Console.WriteLine("Alarm!\a");
Console.WriteLine("Pojedynczy apostrof: \'");
Console.WriteLine("Podejczy cudzysłów: \"");
Console.WriteLine("Znak pusty: \0");
